language: python
matrix:
  include:
  - os: linux
    sudo: required
    python: 3.5
    services:
    - docker
  - os: osx
    language: generic
    before_install:
      - brew update
      - brew install python3
      - virtualenv env -p python3

install:
- pip install cython
- pip install -r requirements.txt
- python setup.py build_ext --inplace
- pip install cibuildwheel==0.5.1
- touch .cibuildwheel

script:
- cibuildwheel --output-dir wheelhouse

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  api_key:
    secure: nsL5ciE295L6IgzsBHbfLDA0/zJmwqR24aCItficHknf1eOQG5vr9QnTNHIIRJC1ic0ANhngx2CCzPDkSt61Q2zIyHaPIOrQ0gLqQcyZld36ZX+PtzfmuAFSEoxGUfZIyc4BDgRNCR2dNj899gMJ8EylbrkpYIllZ9T7k9lwoYA=
  file: wheelhouse/*
  on:
    repo: explosion/preshed
    tags: true
